# Generated by Django 5.1 on 2025-02-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rssfeed',
            old_name='img_url',
            new_name='logo',
        ),
        migrations.AddField(
            model_name='rssfeed',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rssfeed',
            name='custom',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rssfeed',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rssfeed',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
