# Generated by Django 5.1 on 2025-03-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0002_rename_img_url_rssfeed_logo_rssfeed_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeed',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
